version: '3.8'

networks:
  website-net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    
services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    container_name: envoy
    hostname: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 9901:9901
      - 80:80
    networks:
      - website-net

  api:
    build: api
    container_name: api-1
    ports:
      - 8002:8000
    networks:
      - website-net

  website:
    build: website
    container_name: ws-1
    ports:
      - 8003:8000
    networks:
      - website-net

  db:
    image: mysql:latest
    container_name: db-1
    restart: always
    volumes:
      - ./init_mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - website-net


